project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of <Not Safe for Work>"
  author: "Jack Stewart"
  page-footer:
    left: "Copyright 2025, Jack Stewart"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - draft-exec-summary.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



