project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of Not Safe for Work"
  author: "Jack Stewart"
  page-footer:
    left: "Copyright 2025, Jack Stewart"
  chapters:
    - index.qmd
    - Introduction.qmd
    - Methods.qmd
    - Results.qmd
    - Conclusion.qmd
    - References.qmd
  appendices:
    - Data Documentation.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



