---
title: "Conclusion"
format: html
---

While in this report, it is true that non-office workers experience a substantially higher number of workplace injuries, 1.6 million more annually, than their office counterparts, the analysis reveals that office environments present significant safety risks. With over 630,000 injury cases reported among office workers and a higher proportional rate of falls (.22 vs .19), the data highlights the need for greater attention to office safety measures. Additionally, falls in office settings are more severe and result in longer recovery times, averaging over 50 additional days away than non-office workers.

The findings in this report suggest that office environments are not immune to serious injuries. These injuries can result from ergonomic issues, like office chair discomfort, or from a lack of fall prevention measures. A review of existing office safety policies and employee training is recommended to protect office staff and reduce downtime due to preventable injuries.

The report’s results may be limited due to the underreporting of injuries on the job. Employees may consider injuries to be insignificant and do not report them. Additionally, some sectors may have different safety protocols. Compared to an office setting, manufacturing sectors will typically have stricter safety protocols due to union and OSHA oversight. 