# Data Documentation {.unnumbered}

All three datasets cover private, state, and local government wage and salary workers.   The private sector includes a sample of approximately 230,000 establishments, using a mandatory survey from BLS for private sector establishments to generate detailed estimates. All cases should have been reported to OSHA. However, a worker may be injured or ill but doesn’t tell their supervisor and never gets reported. The three datasets come from employers’ records, which OSHA requires.

The following definitions of nonfatal occupational injuries and illnesses used in SOII are the same as those established in the recordkeeping guidelines of OSHA. Nonfatal recordable workplace injuries and illnesses are those that result in any one or more of the following:

-   Loss of consciousness

-   Days away from work

-   Restricted work activity or job transfer

-   Medical treatment beyond first aid

-   etc

@bureauoflaborstatistics64DetailedEvent2023 set R64 Detailed event or exposure by industry division

Variables of Interest

-   **Event or exposure** is how the injury or illness was produced or inflicted, such as caught in running equipment; slips, trips, or falls; overexertion; or contact with electrical current.

-   I**ndustries** are classified into goods-producing, like construction, and service-producing, like financial activities (including real estate and insurance), as laid out in the NCAIS codebook.

-   The number of cases reported per industry and event is the numerical measurement.

The US Bureau of Labor Statistics collected data for 2021 and 2022 from injury reports from businesses in the US. The data collected helps to make insights that can reduce injuries in the workplace. The data contains information about injury-related events and how many events happen in various good-producing and service-providing industries. Employers must file injury data due to OSHA laws to disclose workplace injuries and illnesses.

The data is in Excel and contains entries with 0's. The injury events are in the first column, and the number of these events in various industries is in the other columns. Comparing the number of injuries in the goods vs services sector would be useful to see if injuries happen more often between non-office and office workers. Data analysis can be run to see if specific industries are correlated to certain injury events. Additionally, this data could help predict the likelihood of injury events and detect trends to see if improvements are happening.

@bureauoflaborstatistics67DetailedNature2023 set R67 Detailed nature by number of days by case type

Variables of Interest

-   **The nature of injury or illness** is the physical characteristics of the disabling injury or illness, such as cuts and lacerations, fractures, sprains and strains, or electrocution.

-   The number of days away from **(DFAW)** by case type is the numerical measurement

-   Days away from work (DAFW) cases result in the number of calendar, not work, days away from work (beyond the day of injury or onset of illness).

This data source shows the severity of the hundreds of various occupational injuries by the days of work missed. The first column shows the nature of the injury, and the other columns show the number of cases with a corresponding number of missed days. This dataset is from the US Bureau of Labor Statistics, which gets its data from law-required reporting from US workplaces. The data is helpful as it can illustrate how severe and common specific injuries are. It would be essential to determine what type of injuries most frequently occur in an office versus a non-office setting. Finding the most common and severe injuries by number of days through data analysis would be a priority.

@bureauoflaborstatisticsR10DetailedOccupation2023 R10 Detailed occupation by selected parts of the body affected

Variables of Interest

-   **Part of the body affected** is the part of the body directly linked to the nature of injury or illness cited, such as a finger, arm, back, or body system.

-   SOC and NCAIS systems are used to determine which jobs group into each occupation through serial codes

-   Selected part of the body affected can be diagnosed by a physician/doctor

-   Numerical count cases distinguishing lower and upper extremity injuries for each occupation listed

This dataset is also from OSHA and the BLS office injury page, showing the number of injuries and body parts per occupation. Employers report data by law, and the dataset was published in 2023. The first column contains thousands of occupations, the count of total cases, and a breakdown of body parts where they occur for each occupation. The data illustrates what body parts are injury-prone for office vs. nonoffice occupations. The data analysis could spot trends in body part injuries to create policy changes to prevent certain injuries from occurring. Regression could also predict the likelihood of a particular injury occurring.

\
\
